services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=hotel'
      - 'POSTGRES_PASSWORD=1234'
      - 'POSTGRES_USER=dev'
    ports:
      - '5432:5432'
  redis:
    image: 'redis/redis-stack:latest'
    ports:
      - '6379:6379'
      - '8001:8001'